language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: CS_CHECK=1
    - php: 7.1
      env: CODE_COVERAGE=1
    - php: nightly

cache:
  directories:
    - $HOME/.composer

install:
  - composer install --prefer-dist

script:
  - sh .travis.run-tests.sh

notifications:
  email: false
